# Consistency Checker Configuration

# Global settings
settings:
  # Maximum number of issues to report per file before truncating
  max_issues_per_file: 50
  
  # Enable parallel execution of rules
  parallel_execution: true
  
  # Show detailed timing information
  show_timing: false
  
  # Enable debug mode for troubleshooting
  debug: false
  
  # Output format preferences
  default_output_format: "console"  # console, html, json, csv
  
  # Report generation settings
  generate_html_reports: true
  html_report_path: "reports/consistency_report.html"
  
  # Performance settings
  enable_caching: true
  cache_duration_hours: 24

# File patterns to include in checks
file_patterns:
  - "**/*.py"
  - "**/*.pyx"  # Cython files

# Patterns to exclude from all checks
exclude_patterns:
  - "**/__pycache__/**"
  - "**/.*/**"
  - "**/venv/**"
  - "**/env/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/.git/**"
  - "**/node_modules/**"
  - "**/*.pyc"
  - "**/*.pyo"
  - "**/migrations/**"  # Database migrations often auto-generated
  - "**/third_party/**" # External code

# Rule configuration
rules:
  # Explicitly enabled rules (empty list means all available rules are enabled)
  enabled_rules: 
    - "python_imports"
    - "code_complexity"
    - "naming_conventions"
    
  # Explicitly disabled rules
  disabled_rules:
    - "rule_template"  # This is just a template, not a real rule
    
  # Rule-specific configuration
  rule_config:
    python_imports:
      check_unused: true
      check_order: true
      check_wildcards: true
      allow_wildcard_in_init: true
      ignore_test_imports: true
      
    code_complexity:
      max_cyclomatic_complexity: 10
      max_nesting_depth: 4
      max_function_length: 50
      max_class_methods: 20
      ignore_test_files: true
      
    naming_conventions:
      variable_style: "snake_case"
      function_style: "snake_case"
      class_style: "PascalCase"
      constant_style: "UPPER_SNAKE_CASE"
      max_name_length: 50
      
    line_length:
      max_length: 88  # Black formatter standard
      ignore_comments: true
      ignore_imports: false
      ignore_strings: false

# Integration settings
integration:
  # Pre-commit hook configuration
  pre_commit:
    enabled: true
    rules: ["python_imports", "code_complexity"]
    fail_on_error: true
    
  # CI/CD pipeline integration
  ci_cd:
    enabled: true
    rules: ["python_imports", "code_complexity"]
    generate_reports: true
    fail_on_error: true
    
  # IDE integration
  ide:
    enabled: true
    real_time_checking: true
    rules: ["python_imports"]

# Notification settings
notifications:
  # Waiver expiration notifications
  waiver_expiry:
    enabled: true
    warning_days: 14
    notification_email: "team-lead@company.com"
    
  # Rule failure notifications
  rule_failures:
    enabled: false
    critical_only: true
    notification_email: "dev-team@company.com"

# Reporting configuration
reporting:
  # Console output settings
  console:
    show_progress: true
    show_timing: true
    max_violations_shown: 20
    color_output: true
    
  # HTML report settings
  html:
    template: "default"
    include_source_snippets: true
    include_fix_suggestions: true
    interactive_filtering: true
    
  # JSON report settings
  json:
    pretty_print: true
    include_metadata: true
    schema_version: "1.0"
    
  # CSV report settings
  csv:
    include_headers: true
    delimiter: ","
    quote_strings: true
    
  naming_conventions:
    # DISABLED: This entire rule is disabled via disabled_rules above
    # These settings are kept for reference only
    enforce_snake_case: false
    enforce_pascal_case: false  # Also disable to avoid conflicts
    enforce_upper_case_constants: true
    min_variable_name_length: 2
    allow_single_letter_loop_vars: true
    
# Severity levels to report
severity_levels:
  - "error"
  - "warning"
  - "info"

# Integration settings
integrations:
  # Pre-commit hook configuration
  pre_commit:
    enabled: false
    fail_on_errors: true
    fail_on_warnings: false
    
  # Git hooks
  git_hooks:
    pre_push: false
    pre_commit: false
    
  # CI/CD integration
  ci_cd:
    fail_build_on_errors: true
    fail_build_on_warnings: false
    generate_reports: true
    report_formats: ["text", "json"]

# Output configuration
output:
  # Default report format
  default_format: "text"
  
  # Include waived issues in reports
  show_waived_issues: true
  
  # Include performance statistics
  show_performance_stats: true
  
  # Color output (for terminal)
  use_colors: true
  
  # Verbose output
  verbose: false

# Notification settings
notifications:
  # Notify when waivers are about to expire
  waiver_expiry_warning_days: 7
  
  # Notify when too many waivers exist
  max_waivers_per_file: 5
  max_waivers_per_rule: 20
