# Centralized Lint and Consistency Waivers Configuration
#
# This is the single source of truth for all waivers across CI/CD pipeline and local checks.
# Both GitHub Actions linting and local consistency checker use this file.

# Global waiver settings
settings:
  # Default expiration for waivers without explicit expiry (in days)
  default_expiry_days: 90
  
  # Notify when waivers are about to expire
  expiry_warning_days: 14
  
  # Maximum waivers per file before requiring review
  max_waivers_per_file: 10
  
  # Rules that require security team approval
  security_critical_rules: ["S101", "S102", "B101", "B102", "B601", "B602"]

# Rule-based waivers (applies to entire file/rule combination)
rule_waivers:
  - file: "src/core_module.py"
    rule: "E501"  # Line too long
    reason: "Core module with complex algorithms that cannot be easily refactored"
    approved_by: "tech-lead@company.com"
    expires: "2025-12-31"
    issue_reference: "issue-456"
    
  - file: "pandora_tc_ext_fm.py"
    rule: "F401"  # Unused import
    reason: "Example script with multiple imports for demonstration purposes"
    approved_by: "project-lead@company.com"
    expires: "2025-08-31"

# Line-specific waivers (applies to exact code lines)
line_waivers:
  # Format: Copy the exact violation line from lint output
  - violation_line: "src/config.py:45:80: E501 line too long (120 > 79 characters)"
    code_content: "DATABASE_URL = 'postgresql://user:password@very-long-hostname.example.com:5432/database_name_that_is_also_very_long'"
    reason: "Database URL cannot be broken across lines due to configuration parser limitations"
    approved_by: "senior-dev@company.com"
    expires: "2025-06-30"
    issue_reference: "issue-789"
    
  - violation_line: "src/api/endpoints.py:78:1: F401 'logging' imported but unused"
    code_content: "import logging  # Used in debug mode via dynamic imports"
    reason: "Import used conditionally in debug mode, removing would break debugging"
    approved_by: "api-team-lead@company.com"
    expires: "2025-08-15"
    
  - violation_line: "pandora_tc_ext_fm.py:10:1: F401 'shutil' imported but unused"
    code_content: "import shutil"
    reason: "Import used in conditional code paths for file operations"
    approved_by: "project-lead@company.com"
    expires: "2025-07-31"

# Bulk waivers for repeated patterns
bulk_waivers:
  # Waive all E501 in specific directories
  - pattern: "tests/**/*.py"
    rules: ["E501", "F841"]
    reason: "Test files can have longer lines and unused variables for setup/teardown"
    approved_by: "qa-lead@company.com"
    expires: "2026-01-01"
    
  - pattern: "docs/**/*.py"
    rules: ["E501", "F401", "W293"]
    reason: "Documentation code snippets should not be modified"
    approved_by: "docs-admin@company.com"
    
  - pattern: "third_party/**/*.py"
    rules: "*"  # All rules
    reason: "External code not under our control"
    approved_by: "tech-lead@company.com"
    
  - pattern: "examples/**/*.py"
    rules: ["F401", "E501", "W503"]
    reason: "Example files may have relaxed standards for educational purposes"
    approved_by: "documentation-team@company.com"
    expires: "2025-12-31"

# Consistency checker specific waivers
consistency_waivers:
  # Python imports rule specific waivers
  python_imports:
    file_waivers:
      - pattern: "__init__.py"
        reason: "Init files may have special import patterns"
        
    line_waivers:
      - file: "src/module.py"
        line: 15
        reason: "Import order required for dynamic loading"
        approved_by: "senior-dev@company.com"
        
  # Naming conventions rule specific waivers  
  naming_conventions:
    file_waivers:
      - pattern: "tests/**/*.py"
        reason: "Test files may have descriptive function names that are longer"
        
    pattern_waivers:
      - file_pattern: "src/core/*"
        message_pattern: "*should use snake_case*"
        reason: "Core modules follow established naming conventions"
        approved_by: "tech-lead@company.com"
        expires: "2026-01-01"

# Waiver Rules and Guidelines:
#
# 1. Required Fields:
#    - file/pattern: Path to the file or pattern (can be partial path with wildcards)
#    - rule/rules: Specific lint rule code (e.g., E501, W503, F401) or list
#    - reason: Clear explanation of why the waiver is needed
#    - approved_by: Email of the person who approved this waiver
#
# 2. Optional Fields:
#    - expires: Expiration date in YYYY-MM-DD format
#    - issue_reference: GitHub issue number for tracking
#    - review_date: Date when this waiver should be reviewed
#    - code_content: For line-specific waivers, the actual code being waived
#
# 3. Best Practices:
#    - Use waivers sparingly - fix the issue when possible
#    - Set reasonable expiration dates
#    - Include specific reasons, not generic ones
#    - Get proper approval from tech leads
#    - Review and clean up expired waivers regularly
#    - Reference GitHub issues for tracking and discussion
#
# 4. Common Lint Rules:
#    - E501: Line too long
#    - W503: Line break before binary operator
#    - E203: Whitespace before ':'
#    - F401: Imported but unused
#    - F841: Local variable assigned but never used
#    - N806: Variable name should be lowercase
#    - C901: Function too complex
#    - B008: Do not perform function calls in argument defaults
#    - B101, B102: Security-related hardcoded passwords/keys
#    - S101, S102: Security-related assert usage/exec usage
