name: Python Lint Check

on:
  push:
    paths:
      - '**.py'  # Only run on Python file changes

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to properly determine changed files
      
      - name: Run Python Linting
        id: linting
        uses: ./.github/actions/python-lint
        with:
          changed-only: 'true'  # Only lint changed files
        continue-on-error: true  # This allows the next steps to run even if linting fails
      
      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: ./lint_results.log
          retention-days: 7
      
      - name: Check linting status
        if: steps.linting.outputs.lint-result == 'fail'
        run: |
          echo "Linting failed! Please fix the issues before pushing."
          exit 1