# ==============================================================================
# Simple Pull Request Validation
# ==============================================================================
# Description:
# This workflow validates PRs by ensuring:
# 1. The source branch has no open lint issues
# 2. Basic quality checks pass
# 3. Auto-approves merge if all checks pass
#
# ==============================================================================

name: Simple PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

concurrency:
  group: pr-validation-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  issues: read
  statuses: write

jobs:
  validate_pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # -------------------------------------------------------------------------
      # Step 1: Checkout repository
      # -------------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------------------------------------------------------
      # Step 2: Check for open lint issues on source branch
      # -------------------------------------------------------------------------
      - name: Check for open lint issues
        id: check-issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = "${{ github.event.pull_request.head.ref }}";
            
            console.log(`🔍 Checking for open lint issues on branch: ${branchName}`);
            
            // Search for open lint issues on this branch
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['lint-failure', `branch:${branchName}`],
              per_page: 100,
            });
            
            const openIssues = issues.data.filter(issue =>
              issue.title.includes(`Lint Failure in branch "${branchName}"`)
            );
            
            if (openIssues.length > 0) {
              console.log(`❌ Found ${openIssues.length} open lint issue(s) on branch ${branchName}`);
              core.setFailed(`Branch ${branchName} has ${openIssues.length} open lint issue(s). Please fix them before merging.`);
              
              // Create a comment with issue details
              const issueLinks = openIssues.map(issue => `#${issue.number}`).join(', ');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `❌ **PR Validation Failed**\n\nThe source branch \`${branchName}\` has open lint issues: ${issueLinks}\n\nPlease fix these issues before the PR can be merged.`
              });
              
              return false;
            } else {
              console.log(`✅ No open lint issues found on branch ${branchName}`);
              return true;
            }

      # -------------------------------------------------------------------------
      # Step 3: Basic quality check
      # -------------------------------------------------------------------------
      - name: Basic quality check
        if: steps.check-issues.outcome == 'success'
        run: |
          echo "🔍 Running basic quality checks..."
          
          # Check for Python syntax errors
          PYTHON_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} --diff-filter=AM | grep '\.py$' || true)
          
          if [ -n "$PYTHON_FILES" ]; then
            echo "📁 Checking Python files: $PYTHON_FILES"
            
            for file in $PYTHON_FILES; do
              if [ -f "$file" ]; then
                echo "   Checking syntax: $file"
                python -m py_compile "$file"
                if [ $? -ne 0 ]; then
                  echo "❌ Syntax error in $file"
                  exit 1
                fi
              fi
            done
            
            echo "✅ All Python files have valid syntax"
          else
            echo "ℹ️ No Python files changed"
          fi
          
          echo "✅ Basic quality checks passed"

      # -------------------------------------------------------------------------
      # Step 4: Update PR status and auto-approve if successful
      # -------------------------------------------------------------------------
      - name: Update PR status and auto-approve
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issuesResult = '${{ steps.check-issues.outcome }}';
            const qualityResult = '${{ job.status }}';
            
            let message, description;
            
            if (issuesResult === 'success' && qualityResult === 'success') {
              message = '✅ PR Validation Passed';
              description = 'No open lint issues and quality checks passed';
              
              // Add success comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `✅ **PR Validation Passed**\n\n- ✅ No open lint issues on source branch\n- ✅ Basic quality checks passed\n\n🎉 **Auto-approving this PR** - ready for merge!`
              });
              
              // Auto-approve the PR
              try {
                await github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  event: 'APPROVE',
                  body: '🤖 **Automated Approval**\n\nThis PR has passed all validation checks:\n- ✅ No open lint issues\n- ✅ Basic quality checks passed\n\nApproved automatically by the PR validation workflow.'
                });
                console.log('✅ PR automatically approved');
              } catch (error) {
                console.log('⚠️ Could not auto-approve PR:', error.message);
                // Continue without failing the workflow
              }
            } else {
              message = '❌ PR Validation Failed';
              description = 'Open lint issues or quality checks failed';
              
              // Add failure comment (no auto-approval)
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `❌ **PR Validation Failed**\n\nPlease fix the issues before this PR can be approved and merged.`
              });
            }
            
            console.log(`${message}: ${description}`);

# ==============================================================================
# Workflow Helper Functions and Utilities
# 
# Useful Commands for Debugging:
# 
# 1. Test Configuration Locally:
#    python -c "import yaml; print('✅ Valid' if yaml.safe_load(open('.github/pr-test-config.yml')) else '❌ Invalid')"
# 
# 2. View Current Thresholds:
#    grep -E "(auto_merge_threshold|manual_review_threshold)" .github/pr-test-config.yml
# 
# 3. Check Workflow Syntax:
#    act --list  # if you have 'act' installed for local testing
# 
# 4. Backup Configuration:
#    cp .github/pr-test-config.yml .github/pr-test-config.yml.$(date +%Y%m%d)
# 
# 5. View Validation History:
#    gh api repos/:owner/:repo/actions/runs --jq '.workflow_runs[].conclusion' | head -10
# 
# 6. Re-run Failed Validation:
#    gh api repos/:owner/:repo/actions/runs/:run_id/rerun
# 
# Troubleshooting:
# 
# • Snake case still being enforced?
#   Check: devops/consistency_checker/checker_config.yml
#   Ensure: naming_conventions is in disabled_rules
# 
# • Hard checks failing?
#   Review: Security scan results and syntax errors
#   Fix: Critical vulnerabilities and Python syntax issues
# 
# • Low scores?
#   Improve: Test coverage, documentation, linting
#   Consider: Adjusting weights in pr-test-config.yml
# 
# • Auto-merge not working?
#   Verify: Score ≥ auto_merge_threshold
#   Check: All hard checks passed
#   Ensure: Required GitHub checks are enabled
# 
# Documentation: devops/docs/pr-validation.md
# Support: devops-team@company.com
# ==============================================================================
